.MODEL SMALL
.DATA
MSG1 DB 0DH,0AH, "ENTER ALPHANUMERIC NUMBER...$"
REST DB 02 DUP(0)
.CODE
MOV AX,@DATA
MOV DS,AX
LEA DX,MSG1
CALL DISP
MOV AH,01H
INT 21H
MOV BL,AL
MOV CL,4
SHR AL,CL
CMP AL,0AH
JC DIGIT
ADD AL,0FH
DIGIT: ADD AL,30H
       MOV REST,AL
       AND BL,0FH
       CMP BL,0AH
       JC DIGIT1
       ADD AL,07H
DIGIT1: ADD BL,30H
        MOV REST+1,BL
        MOV AH,00H
        MOV AL,03H
        INT 10H
        MOV AH,02H
        MOV BH,00H
        MOV DH,18H
        MOV DL,26H
        INT 10H
        MOV REST+2,'$'
        LEA DX,REST
        CALL DISP
        MOV AH,4CH
        INT 21H
DISP PROC NEAR
MOV AH,09H
INT 21H
RET
DISP ENDP
END
